language: r

before_install:
  - cd dvisR

cache: packages

r_binary_packages:
    - MASS
    - hash
    - xgboost
    - uwot
    - plyr
    - igraph

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: true
